### ISSUE TITLE
[Chore] Improve asynchronous processing of keywords

### ISSUE THREAD

**Issue by olivierobert** [skrishnan22/google-scraper#16]
## Issue

While keywords are processed asynchronously, they are processed in a batch per file, so in a loop:

https://github.com/skrishnan22/google-scraper/blob/55c77e1f85ab61491fe977a3d8721851a7b6e16d/api/tasks/scraper.js#L36-L64

 There is no error handling, so if any error occurs in the loop, many keywords could be left in the status `PENDING.` This would make the application brittle.

> [!WARNING]
> While the error status exists in the enum, it is currently not being used.

## Expected

- Keywords should be stored in the database with a flag to track the scraping status ✅ 
- A distinct background job to scrap the Google page for each keyword is then scheduled.

The benefits are:

- Fast CSV upload request
- The scraping of each keyword is isolated, i.e., one could error while others could be successful.

**Comment by skrishnan22** [comment]
Agreed. Since the batch size is limited and small(100) decided to start with this and this also avoids creating a new puppeteer instance per keyword(might be a pre mature optimisation). 

And since Graphile has retry with exponential backoff, the keywords would be eventually processed was my thinking.

But agree, there should be no reason why failure of one keyword , should be an impediment for other keywords in file.

 Will make this change and raise a PR for this in the next 1-2 days

**Comment by olivierobert** [comment]
Since the change would be significant, a fix/PR is not expected. The most important is to understand your reasoning about the current implementation and the issue.
