### ISSUE TITLE
[Chore] Improve scraper test robustness

### ISSUE THREAD

**Issue by olivierobert** [skrishnan22/google-scraper#18]
## Issue

Automated tests do not cover robustly enough the core business logic: scraping. The following test would make an actual HTTP request, which could be unstable:

https://github.com/skrishnan22/google-scraper/blob/55c77e1f85ab61491fe977a3d8721851a7b6e16d/api/tests/scraper.test.js#L78-L90

## Expected

Writing tests for an asynchronous process that makes HTTP requests is where the tricky parts lie. This is why there is an expectation to propose an efficient solution to write robust tests for the scraper, i.e., without making a "real" HTTP request and beyond using file-based fixtures only.

**Comment by skrishnan22** [comment]
Understood. I have used  [nock](https://www.npmjs.com/package/nock) earlier for HTTP interception in tests. Would use that or  Puppeteer's request interception feature to intercept the request to google and send a mock HTML response.

Also, since the request is simple(static url) and no headers involved, interception would only validate if Puppeteer is opening the correct URL. One useful test case could be for when page returns an error response or invalid HTML.

Will work on it, after closing other issues. Please let me know if you feel this should be prioritised.

The intention of adding this test with actual request was ensure if the selectors used in parsing are valid and detect any changes Google makes to the page structure elements. In a scraping product, ideally this would be a cron job to detect changes and notify devs, for simplicity added it as a test.

**Comment by olivierobert** [comment]
I now better understand the intent, which I could not from the submission as-is. It does not need to be prioritized at this stage. Toling-wise, the team usually uses https://netflix.github.io/pollyjs/#/ FYI.

**Comment by skrishnan22** [comment]
Fair, better comments around the tests would have helped convey the intent.

TIL about PollyJS. Will check it out.
