### ISSUE TITLE
[Question] Why use graphile-worker over other solutions?

### ISSUE THREAD

**Issue by olivierobert** [skrishnan22/google-scraper#19]
https://github.com/graphile/worker is a relatively recent and less popular tool than https://github.com/OptimalBits/bull and https://bullmq.io/ to implement background job queues.

See the NPM stats: https://npmtrends.com/bull-vs-bullmq-vs-graphile-worker

<img width="1315" alt="image" src="https://github.com/skrishnan22/google-scraper/assets/696529/9a48f921-9730-449b-a8ea-957ae50e2eaa">

Therefore, what made you decide to use this tool over the existing alternatives?

**Comment by skrishnan22** [comment]
I did consider Bull and RabbitMQ for the queue. The intention was to not add any additional infrastructure dependency(like Redis) with the idea to keep it simple, considering the scale/usage of this project.

So was looking at Postgres backed workers and found Graphile and [PGBoss](https://www.npmjs.com/package/pg-boss?activeTab=readme).

Both were nearly similar in terms of popularity(Github stars and Weekly downloads). But chose Graphile solely because it had else open issues and was more actively maintained compared to PGBoss.

Additionally, Graphile checks most boxes like concurrent job execution, locking mechanism to run multiple consumers and built in retry mechanism which are available in Bull etc.
